// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLabel(arg1, arg2) {
  return window['go']['controllers']['LabelController']['CreateLabel'](arg1, arg2);
}

export function DeleteLabel(arg1) {
  return window['go']['controllers']['LabelController']['DeleteLabel'](arg1);
}

export function GetLabels() {
  return window['go']['controllers']['LabelController']['GetLabels']();
}

export function UpdateLabel(arg1, arg2, arg3) {
  return window['go']['controllers']['LabelController']['UpdateLabel'](arg1, arg2, arg3);
}
