// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateLabel(arg1:string,arg2:string):Promise<models.Label>;

export function DeleteLabel(arg1:number):Promise<void>;

export function GetLabels():Promise<Array<models.Label>>;

export function UpdateLabel(arg1:number,arg2:string,arg3:string):Promise<models.Label>;
