// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSavedTimer() {
  return window['go']['controllers']['TimerController']['GetSavedTimer']();
}

export function GetTimerState() {
  return window['go']['controllers']['TimerController']['GetTimerState']();
}

export function PauseTimer() {
  return window['go']['controllers']['TimerController']['PauseTimer']();
}

export function ResetTimer() {
  return window['go']['controllers']['TimerController']['ResetTimer']();
}

export function RestoreTimer() {
  return window['go']['controllers']['TimerController']['RestoreTimer']();
}

export function ResumeTimer() {
  return window['go']['controllers']['TimerController']['ResumeTimer']();
}

export function StartTimer(arg1, arg2) {
  return window['go']['controllers']['TimerController']['StartTimer'](arg1, arg2);
}

export function StopTimer() {
  return window['go']['controllers']['TimerController']['StopTimer']();
}
