// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSavedTimer():Promise<number>;

export function GetTimerState():Promise<number>;

export function PauseTimer():Promise<void>;

export function ResetTimer():Promise<void>;

export function RestoreTimer():Promise<void>;

export function ResumeTimer():Promise<void>;

export function StartTimer(arg1:number,arg2:any):Promise<void>;

export function StopTimer():Promise<number>;
